apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media
spec:
  capacity:
    storage: 2Ti   # informational only — NFS doesn't enforce this, just needs a value
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.1.242
    path: /mnt/tank/media
