apiVersion: v1
kind: Secret
metadata:
    name: democratic-csi-iscsi-secret
    namespace: democratic-csi
stringData:
    values.yaml: ENC[AES256_GCM,data:PDqxDU31VEknwb1nKXILeFM3ebuTVSyWPhEI1qAZhJtXEwvyFZqGw+OKQUnojo+0/f5jl3JMHCctK8p9CFNjm4OE86abt4kvhO+iOrdZMjnQ+w/A70vEbRfFjlGpXsdVKlfOWO7ZhQMUfTCYuRd4roKkOGu2O019Ew==,iv:IX32garvhlVH20x3CeeNJq74qjgpSQpyxMzv/wyBtkI=,tag:XpRFPs0D1VzcpYiyySjt2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVU85anFZUmxyOTFRa0R1
            T0VJVUxkek9MN1dyZmY5Rm55cHl3NjR2OENZCkdMdEkyUTVqSEF2K0lSb0xBVUw3
            UGZQRVdmQmtSZzFpL0ExUWhaY1VhYncKLS0tIE1rU2JMQlE1R0s2UjMxU0tiNFJn
            d3hSQlV2UzlSd0dLOWxtV05yOEZ2NkUKIlt7nZnM85jFZAVDQmKo0v6EPqapOYPQ
            Q6o6xApMAZ6Y8aiNaciEODAdMr2InQNq77LKBlZrcwUOV9mSNUgSpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eglcp3h040vj06705a42f0tltrqwt5mrxakjem7ep7v8n5a57y0s0cux4w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T01:53:53Z"
    mac: ENC[AES256_GCM,data:y+sd/EaVCcG0Mof7Mzo8RL7lgk3uw0JqgMVM8iZ39y+vubDR1xfdvFr0MOHpzG3ufOYA3EmRWJN7SLav8wGOdQz7nUsxzbvQHnqz8hUxIryG/EI8uH7nZukIFh9tWHhgGL9yy9pyTtYEH1vwDWOuJPCfcbVhhJC/X0JaHKBjoCk=,iv:CEDicXugaoVh0UOjVVyule+HcVAXKk8Y3eS0IQ0yXM0=,tag:30dbATrcIbayeUFvyzMcbw==,type:str]
    version: 3.13.2
