apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
stringData:
    token: ENC[AES256_GCM,data:ogsEVOItXlqrARvg4mJTcoBPHjDgvCyfi33+S0093/0RRu0AM4L70tZfNW1S/3UeW1+E7stEgnH3xU5s7SDMivBkAEkSozERuvH8OuziLpp1kFJ616DKIJtIpKaZCqw5WT1Vgx9NJjmukRICqgwXphspHhteRIQRXmyMGcFBRj9SugPznm/agcBImXM8uoDIfz7EPZMFK3fVAAKLDs46lezqoyuNn2wP2yDeGurHWh3JyR7d5KKQ6w==,iv:XeT0/h9WNrYu+KaSgiGB2Ins2Wd6Aqlz/vkGFF5Gs2w=,tag:75TclQqGN+xGsc366MX3nA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eglcp3h040vj06705a42f0tltrqwt5mrxakjem7ep7v8n5a57y0s0cux4w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WExNS0NVZ1YvbnpSMHN2
            ZXcrazdDUHNwYkJyb0k3TVkzb01GQ1orU0hvClY1aGxDVENuLzF1QmZTV2x0TW1Q
            OVYzay81L01uSHNhWmVRTG9IeFF3Z1UKLS0tIGF5ek8yaGsxM3E1UDc0cFpNeEQ4
            Wld5TVhIaktIRVU0dUlITTdyODNlcmMKjIqwex2b+kgFaz7yK0Y3SqtHbQMKEGvO
            kZ4CFAxdXDK8DcJ0R3orUCd7Up5yZ4wqOFr/1fpbN7bNpyNEs+1rHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T15:59:21Z"
    mac: ENC[AES256_GCM,data:WxdLkDtY9U1oeMmI5Af0RXbxH9esrswoyakjLz0YCY+0El/roPzxWcmbkAvhRnKGhEoZxx9Py6Da51KujBGVYHeC8S/Yg0mnEL/Oav4f07UbKpie9VPzev+XBYdR/MoqULKXwUSMuVhpPibQ37vVpF75WQxKgN6l9MUKR0sLF3w=,iv:gnjOVqX927isdaI3jabrfsj0lvuq6BMvD2MvJduBsGo=,tag:owAdQYkYQuOptijD1eu0uQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
