apiVersion: v1
kind: Secret
metadata:
    name: linkding-superuser
    namespace: linkding
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:aveDTg==,iv:AE5nDh5pnjwmtZl6WSuONfjiFZMNJqvS8AqSCZ8syIE=,tag:An2ETZi6+UozX2CrvFDDvw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:grFuiyJWD1pGUA==,iv:eFRH9CZKElJmsAAh02CwGcrzTO77l9cidYTQsDlYTVQ=,tag:ovtSPannFsy0+D6Syo1AGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eglcp3h040vj06705a42f0tltrqwt5mrxakjem7ep7v8n5a57y0s0cux4w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYXpCNzUvVDY1T05wQUJh
            VUQ4UXl3cVExVk9hVXJXbDhKTGVOTDdZWFdNCnk4VHZGeU5ZQ0ttYk1rcFBSNkth
            b3g3SlUyWVlaWS80M0F3NFA0ek9nN1EKLS0tIFkvNTBCSmM3ckJhZWpzWE1oN2JK
            TW1GdDVxWGRvRDdzbVBNNFR0dFJ5bTgKIZHMvf68KfJJJRgxu+VtidT513p/JHRQ
            +j+nmAs+Ritz8ScqGBrW3NrwzckcVhyi64UTftX0YD/SUoob163LTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T15:01:29Z"
    mac: ENC[AES256_GCM,data:OLbv0+oSCdypq1ZYEfJlW4gTNmi8T3JgHBCNxdJ9sDLbkzve63acnIuJklCw1LufqaWLGxx2UMiNDdRBtsmzlhozhBWsFUyKwwXFUw6LIm5TBL8D0pXQn7dGVGHEtt3q9TDbDgZUdOyEuGBt7GTnlz00NgsisK+ePVQuLd/f2T4=,iv:A/3uTYrrUUvMH+oF0YHKNtuUg8JUP2T4nRG0WeJADbw=,tag:TBkQxUV6SoHjGrCkMgaoeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
